Repository BalancyTeam/balancy-app-backend, pull requests merged in 2023-06, with the labels that each got.

#8 add labeler
  .github/labeler.yml
  .github/workflows/ci.yml
  .github/workflows/folder-labels.yml
Labels: workflows, feature

#12 Feature/add ci linter
  .editorconfig
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-commit
  .ls-lint.yml
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies, workflows, feature, root

#30 feature: add user delete route
  src/users/users.controller.ts
Labels: feature

#37 feature: add email verification
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/common/index.ts
  src/common/services/email.service.ts
  src/common/services/index.ts
  src/common/services/logger.service.ts
  src/common/services/services.ts
  src/config/config-validation-schema.ts
  src/config/index.ts
  src/main.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement, dependencies, feature, root, environment

#44 feature: add password reset
  .env.example
  src/auth/auth.controller.ts
  src/auth/dto/change-password.dto.ts
  src/auth/dto/index.ts
  src/common/services/email.service.ts
  src/config/config-validation-schema.ts
  src/users/entities/user.entity.ts
  src/users/users.service.ts
Labels: enhancement, feature, environment

#46 Update user entity
  src/users/entities/user.entity.ts
Labels: feature

#47 Feature/tasks
  package.json
  src/sub-categories/entities/sub-category.entity.ts
  src/sub-categories/sub-categories.module.ts
  src/sub-categories/sub-categories.service.ts
  src/tasks/dto/create-task.dto.ts
  src/tasks/entities/task.entity.ts
  src/tasks/tasks.controller.ts
  src/tasks/tasks.module.ts
  src/tasks/tasks.service.ts
  src/tasks/types/types-response.interface.ts
  src/users/entities/user.entity.ts
  src/users/users.service.ts
Labels: dependencies, feature, root
